# Generated by Django 4.1.7 on 2023-04-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_phone_phone_alter_phone_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='profiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.profile'),
        ),
    ]
