# Generated by Django 4.1.7 on 2023-04-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_phone_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='verify_code',
            field=models.CharField(max_length=4),
        ),
    ]
