# Generated by Django 4.1.7 on 2023-04-09 21:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_phone_verify_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=datetime.datetime(2023, 4, 9, 21, 15, 57, 330558, tzinfo=datetime.timezone.utc), max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='verify_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
